### ISSUE TITLE
Problema de duplicate Symbol

### ISSUE THREAD

**Issue by rmarku** [UCC-ArquitecturaSoftwareI/primer-parcial-piantoni-virga#4]
https://github.com/UCC-ArquitecturaSoftwareI/primer-parcial-piantoni-virga/blob/a3206cef85ae8aa681c3d9f7de6bd1f75e2ead47/clases/Nave.h#L40

Esta implementación está en el .h  debería estar en el .cpp

**Comment by fpiantoni** [comment]
Gracias Profe, Issue Solucionado.
